### ISSUE TITLE
Reconsider plugin name?

### ISSUE THREAD

**Issue by lindseydiloreto** [fvaldes33/plus#1]
With all due respect, you may have chosen a very poor name for this plugin.

There is a very popular and successful [commercial plugin store](https://craftpl.us/plugins) **which is also named Craft Plus**. That Craft Plus has been around for about 3 years now, and is [extremely well known](https://twitter.com/craftplusapp) within the community.

You're certainly welcome to do what you feel is right, but I would highly encourage you to think of a different name for your plugin. For it to share a name with an unrelated plugin store, I'd imagine that would cause quite a lot of confusion.

**Comment by fvaldes33** [comment]
Craftplus was something we (at UNION) developed internally therefore naming
convention did not matter. I have gone ahead and made the needed changes to
our plugin. Changing it from CraftPlus to just simple Plus (for CraftCMS).

Hope I didnt create any issues.

Franco

**Comment by lindseydiloreto** [comment]
Great, thanks Franco! That's very much appreciated. :)
