### ISSUE TITLE
FR: instantiate services on PlusService instead of PlusVariable

### ISSUE THREAD

**Issue by johndwells** [fvaldes33/plus#3]
We're starting to use Plus as the foundation for dropped in business logic, so in addition to added Behaviors we are taking advantage of the Services feature too.  However since the Services are only intended to be available as a twig variable, we have to instantiate our own copy of a service if we wish to use it in other places (say in the ElementAPI).  It would seem cleaner if Plus's own Service could hold the instantiation and registration of these.

**Comment by fvaldes33** [comment]
@johndwells - Could you provide an example of what you are trying to accomplish?

**Comment by fvaldes33** [comment]
@johndwells - Take a look at my latest commit. I added a function called plus() that will access any service in the Plus\Services namespace through the __get method.

If you are using it outside of craft's namespace then just make sure to add the use function line to gain access to the plus function.

```
use function Craft\plus

then:
plus()->[serviceClassName]->[serviceMethodName]();

example:
plus()->log->write($key, $value);

or:
$logService = plus()->log;
$logService->write($key, $value);
```

**Comment by johndwells** [comment]
Hey, sorry for not responding to this!  This is great, love the addition of `plus()` function. Thanks!
