### ISSUE TITLE
PlusService methods should be "compatible" with CComponent

### ISSUE THREAD

**Issue by johndwells** [fvaldes33/plus#4]
When we have devMode turned on and hit an "error" page (e.g. 404, 500, 503 etc), rather than our error template we get the following stack trace errors:

````
Warning: Declaration of Craft\PlusService::__get(string $name) should be compatible with CComponent::__get($name) in /path/to/craft/plugins/plus/services/PlusService.php on line 203
...
Warning: Declaration of Craft\PlusService::__call(string $name, array $params) should be compatible with CComponent::__call($name, $parameters) in /path/to/craft/plugins/plus/services/PlusService.php on line 203
````

I know it's not _really_ an issue for production but it really gets in the way of development.  So would you be willing to remove the parameter type hinting for `PlusService::__get()` and `PlusService::__call()`?

**Comment by fvaldes33** [comment]
Closing. Only addressing tickets for Craft v3.

**Comment by johndwells** [comment]
Yep fair enough now :)
