### ISSUE TITLE
500 Server Error in Live Preview

### ISSUE THREAD

**Issue by johndwells** [fvaldes33/plus#7]
There are two lines within `BehaviorService.php` which check for the existence of `$_POST['livePreview']`, and if present attempt to set a model attribute by another key/val in `$_POST`. However depending on the context, this key/val might not exist.  This is causing a PHP error to be thrown, rendering Live Preview unusable.

Curiously there's also a comment accompanying the code block that says 

> This *should* be a temporary fix. Ticket open with craft about fixing this

Any chance this _has_ been fixed?

**Comment by fvaldes33** [comment]
@johndwells sorry for the delay on some issues - I encountered this bug too and fixed it locally but never pushed my changes. Adding `?? null` to both the category and section area was the fix. v2.0.4

**Comment by johndwells** [comment]
Nice!

**Comment by johndwells** [comment]
I'm afraid this fix has reared it's head again - we are using Solspace Calendar and when Live Previewing an _event_ that has a _matrix field_ with a block containing an _entry_ field, the following error gets thrown:

`Entry is missing its section ID`

What appears to be happening is that the null coalescing line actually _nullifies_ the entry's sectionId value that already exists.

Would a perhaps more robust conditional be:

```
if (isset($_POST['livePreview'], $_POST['sectionId']) && !isset($element->sectionId)) {
    $element->sectionId = $_POST['sectionId'];
}
```

Cheers,
John

**Comment by johndwells** [comment]
(of course I assume that whatever fix is right would also apply to the `category` behavior attaching...)
